language: node_js
node_js:
- 9
install: npm install
script:
- npm run build
- NODE_DEBUG=gh-pages npm run deploy
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master